version: "3.7"

services:
  server:
    image: ruuviget/server
    build:
      context: ./
      dockerfile: server.dockerfile
    env_file:
      - .env
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z
    privileged: true
    network_mode: "host"
