version: "3.7"

services:
  server:
    profiles: ["server"]
    image: ruuviget/server
    build:
      context: ./
      dockerfile: server.dockerfile
    env_file:
      - .env
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z
    privileged: true
    network_mode: "host"

  commandline-client:
    profiles: ["client"]
    image: ruuviget/commandline-client
    build:
      context: ./
      dockerfile: commandline-client.dockerfile
    environment:
      RUUVI_CLI_REPETITION_IN_SECONDS: 30
    env_file:
      - .env
